MAPKIT_API_KEY=sample_key
IIKO_API_KEY=sample_key
TG_BOT_TOKEN=1234567890:ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
TG_CHANNEL_ID=-12345678910
DEV_TG_CHAT_ID=12345678910
SERVER_BASE_URL=http://1.123.45.67:0000/
MANDARIN_API_KEY=sample_key