[versions]
versionCode = "3"
versionName = "1.03kmp"
compileSdk = "36"
minSdk = "26"
targetSdk = "35"
java = "VERSION_17"
appcompatVersion = "1.7.1"
koin = "4.1.1"
ktor = "3.3.1"
kamel = "1.0.8"
lifecycleVersion = "2.9.5"
material3Version = "1.4.0"
playServicesLocationVersion = "21.3.0"
composeMultiplatform = "1.9.1"
activity = "1.11.0"
agp = "8.13.0"
composeBom = "2025.10.00"
navigation = "2.9.1"
coreKtx = "1.17.0"
detekt = "1.23.8"
firebaseCrashlytics = "3.0.4"
googleService = "4.4.3"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.20"
kotlinx-datetime = "0.7.1"
ksp = "2.2.20-2.0.2"
#noinspection NewerVersionAvailable
mapkit = "4.25.0-full"
material = "1.13.0"
parcelize = "2.2.20"
pulltorefresh = "1.7.0"
sqldelight = "2.1.0"
kotlinx-serialization = "1.9.0"
kotlinStdlibVersion = "2.2.20"
kotlinTestVersion = "2.2.20"
napier = "2.7.1"
moko-resources = "0.25.1"
runnerVersion = "1.7.0"
coreVersion = "1.7.0"
datastore = "1.1.7"
pullrefresh = "1.4.0-beta03"
urlencoderLib = "1.6.0"


[libraries]
# AndroidX
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }

# Мультиплатформенные ViewModel и Runtime
jetbrains-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycleVersion" }
jetbrains-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleVersion" }
jetbrains-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleVersion" }

# Kamel
kamel-image-default = { module = "media.kamel:kamel-image-default", version.ref = "kamel" }

# Detekt
staticAnalysis-detektCli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
staticAnalysis-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
staticAnalysis-detektLibraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }

# Firebase
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "19.0.2" }

# Napier(логгер)
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

# MapKit
com-yandex-maps-mobile = { group = "com.yandex.android", name = "maps.mobile", version.ref = "mapkit" }

# Material для androidMain
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }

# SQLDelight
sqldelight = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }

# Ktor
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

# Kotlinx Serialization
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlibVersion" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTestVersion" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runnerVersion" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "coreVersion" }

# DataStore
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Google Play Services Location
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }

# MOKO Resources
resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }
resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "moko-resources" }

# Navigation Compose (навигация)
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }

# URL encoder
urlencoder-lib = { module = "net.thauvin.erik.urlencoder:urlencoder-lib", version.ref = "urlencoderLib" }

#  Pull to refresh
materii-pullrefresh = { group = "dev.materii.pullrefresh", name = "pullrefresh", version.ref = "pullrefresh" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleService" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "parcelize" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }