name: PR checks

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
permissions:
  contents: read
  pull-requests: write

env:
  commonGradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
  detektReportPath: ./build/reports/detekt/detekt.xml
  reviewdogSetup: -f=checkstyle -name="detekt" -level=error -filter-mode=added

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cleanup Github-Actions bot comments
        continue-on-error: true
        run: |
          sh ./ci/github_comments_cleanup.sh "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" "github-actions[bot]" "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Setup JDK 21 for build
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create google-services.json from secret
        run: |
          mkdir -p composeApp/src/androidMain
          echo '${{ secrets.GOOGLE_SERVICES_JSON_RELEASE }}' > composeApp/google-services.json
          echo '${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}' > composeApp/src/androidMain/google-services.json

      - name: Create apikeys.properties from secrets
        run: |
          printf "MAPKIT_API_KEY=%s\nIIKO_API_KEY=%s\nTG_BOT_TOKEN=%s\nTG_CHANNEL_ID=%s\nDEV_TG_CHAT_ID=%s\nSERVER_BASE_URL=%s\nMANDARIN_API_KEY=%s\nYOOKASSA_CLIENT_APPLICATION_KEY=%s\nYOOKASSA_SHOP_ID=%s\n" \
            "$MAPKIT_API_KEY" "$IIKO_API_KEY" "$TG_BOT_TOKEN" "$TG_CHANNEL_ID" "$DEV_TG_CHAT_ID" "$SERVER_BASE_URL" "$MANDARIN_API_KEY" "$YOOKASSA_CLIENT_APPLICATION_KEY" "$YOOKASSA_SHOP_ID" \
            > apikeys.properties
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          MAPKIT_API_KEY: ${{ secrets.MAPKIT_API_KEY }}
          IIKO_API_KEY: ${{ secrets.IIKO_API_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}
          DEV_TG_CHAT_ID: ${{ secrets.DEV_TG_CHAT_ID }}
          SERVER_BASE_URL: ${{ secrets.SERVER_BASE_URL }}
          MANDARIN_API_KEY: ${{ secrets.MANDARIN_API_KEY }}
          YOOKASSA_CLIENT_APPLICATION_KEY: ${{ secrets.YOOKASSA_CLIENT_APPLICATION_KEY }}
          YOOKASSA_SHOP_ID: ${{ secrets.YOOKASSA_SHOP_ID }}

      - name: Run detekt
        run: ./gradlew detektAll $commonGradleFlags
        continue-on-error: true

      - name: Run Reviewdog for Detekt as Github Review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog $reviewdogSetup -reporter=github-pr-review <$detektReportPath

      - name: Run Reviewdog for Detekt as Github CHECK
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog $reviewdogSetup -reporter=github-pr-check <$detektReportPath

  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 21 for build
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create google-services.json from secret
        run: |
          mkdir -p composeApp/src/androidMain
          echo '${{ secrets.GOOGLE_SERVICES_JSON_RELEASE }}' > composeApp/google-services.json
          echo '${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}' > composeApp/src/androidMain/google-services.json

      - name: Create apikeys.properties from secrets
        run: |
          printf "MAPKIT_API_KEY=%s\nIIKO_API_KEY=%s\nTG_BOT_TOKEN=%s\nTG_CHANNEL_ID=%s\nDEV_TG_CHAT_ID=%s\nSERVER_BASE_URL=%s\nMANDARIN_API_KEY=%s\nYOOKASSA_CLIENT_APPLICATION_KEY=%s\nYOOKASSA_SHOP_ID=%s\n" \
            "$MAPKIT_API_KEY" "$IIKO_API_KEY" "$TG_BOT_TOKEN" "$TG_CHANNEL_ID" "$DEV_TG_CHAT_ID" "$SERVER_BASE_URL" "$MANDARIN_API_KEY" "$YOOKASSA_CLIENT_APPLICATION_KEY" "$YOOKASSA_SHOP_ID" \
            > apikeys.properties
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          MAPKIT_API_KEY: ${{ secrets.MAPKIT_API_KEY }}
          IIKO_API_KEY: ${{ secrets.IIKO_API_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}
          DEV_TG_CHAT_ID: ${{ secrets.DEV_TG_CHAT_ID }}
          SERVER_BASE_URL: ${{ secrets.SERVER_BASE_URL }}
          MANDARIN_API_KEY: ${{ secrets.MANDARIN_API_KEY }}
          YOOKASSA_CLIENT_APPLICATION_KEY: ${{ secrets.YOOKASSA_CLIENT_APPLICATION_KEY }}
          YOOKASSA_SHOP_ID: ${{ secrets.YOOKASSA_SHOP_ID }}

      - name: Assemble composeApp
        run: ./gradlew :composeApp:assembleDebug $commonGradleFlags


      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: composeApp-debug.apk
          path: composeApp/build/outputs/apk/debug/*.apk
          retention-days: 3